datasets:
  cifar100:
    name: &dataset_name 'cifar100'
    type: 'CIFAR100'
    root: &root_dir !join ['./resource/dataset/', *dataset_name]
    splits:
      train:
        dataset_id: &cifar100_train !join [*dataset_name, '/train']
        kwargs:
          root: *root_dir
          train: True
          download: True
          transform_configs:
            - type: 'RandomCrop'
              kwargs:
                size: 32
                padding: 4
            - type: 'RandomHorizontalFlip'
              kwargs:
                p: 0.5
            - type: 'ToTensor'
              kwargs:
            - &normalize
              type: 'Normalize'
              kwargs:
                mean: [0.5070754, 0.48655024, 0.44091907]
                std: [0.26733398, 0.25643876, 0.2761503]
      val:
        dataset_id: &cifar100_val !join [*dataset_name, '/val']
        kwargs:
          root: *root_dir
          train: False
          download: True
          transform_configs: &val_transform
            - type: 'ToTensor'
              kwargs:
            - *normalize
      test:
        dataset_id: &cifar100_test !join [*dataset_name, '/test']
        kwargs:
          root: *root_dir
          train: False
          download: True
          transform_configs: *val_transform

models:
  model:
    name: &student_model_name 'wide_resnet28_10'
    kwargs:
      dropout_p: 0.0
      num_classes: 100
      pretrained: False
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_name]
    ckpt: !join ['./resource/ckpt/', *dataset_name, '/ce/', *student_experiment, '.pt']

train:
  log_freq: 100
  num_epochs: 200
  train_data_loader:
    dataset_id: *cifar100_train
    random_sample: True
    batch_size: 128
    num_workers: 16
    cache_output:
  val_data_loader:
    dataset_id: *cifar100_val
    random_sample: False
    batch_size: 128
    num_workers: 16
  model:
    adaptations:
    sequential: []
    wrapper: 'DistributedDataParallel'
    requires_grad: True
    frozen_modules: []
  optimizer:
    type: 'SGD'
    kwargs:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0005
  scheduler:
    type: 'MultiStepLR'
    kwargs:
      milestones: [60, 120, 160]
      gamma: 0.2
  criterion:
    type: 'WeightedSumLoss'
    kwargs:
      sub_terms:
        ce:
          criterion:
            type: 'CrossEntropyLoss'
            kwargs:
              reduction: 'mean'
          criterion_wrapper:
            type: 'SimpleLossWrapper'
            kwargs:
              input:
                is_from_teacher: False
                module_path: '.'
                io: 'output'
              target:
                uses_label: True
          factor: 1.0

test:
  test_data_loader:
    dataset_id: *cifar100_test
    random_sample: False
    batch_size: 1
    num_workers: 16
