datasets:
    ilsvrc2012:
        name: &dataset_name 'ilsvrc2012'
        type: 'ImageFolder'
        root: &root_dir !join ['./resource/dataset/', *dataset_name]
        splits:
            train:
                dataset_id: &imagenet_train !join [*dataset_name, '/train']
                params:
                    root: !join [*root_dir, '/train']
                    transform_params:
                        0:
                            type: 'RandomResizedCrop'
                            params:
                                size: &input_size [224, 224]
                        1:
                            type: 'RandomHorizontalFlip'
                            params:
                                p: 0.5
                        2: &totensor
                            type: 'ToTensor'
                            params:
                        3: &normalize
                            type: 'Normalize'
                            params:
                                mean: [0.485, 0.456, 0.406]
                                std: [0.229, 0.224, 0.225]
            val:
                dataset_id: &imagenet_val !join [*dataset_name, '/val']
                params:
                    root: !join [*root_dir, '/val']
                    transform_params:
                        0:
                            type: 'Resize'
                            params:
                                size: 256
                        1:
                            type: 'CenterCrop'
                            params:
                                size: *input_size
                        2: *totensor
                        3: *normalize

models:
    teacher_model:
        name: &teacher_model_name 'resnet152'
        params:
            num_classes: 1000
            pretrained: True
        experiment: &teacher_experiment !join [*dataset_name, '-', *teacher_model_name]
        ckpt: !join ['./resource/ckpt/image_classification/teacher/', *teacher_experiment, '.pt']

    student_model:
        name: &student_model_name 'resnet18'
        params:
            num_classes: 1000
            pretrained: True
        experiment: &student_experiment !join [*dataset_name, '-', *student_model_name, '_from_', *teacher_model_name]
        ckpt: !join ['./resource/ckpt/image_classification/single_stage/pkt/', *student_experiment, '.pt']

train:
    log_freq: 1000
    num_epochs: 20
    train_data_loader:
        dataset_id: *imagenet_train
        random_sample: True
        batch_size: 32
        num_workers: 16
        cache_output:
    val_data_loader:
        dataset_id: *imagenet_val
        random_sample: False
        batch_size: 32
        num_workers: 16
    teacher:
        sequential: []
        forward_hook:
            input: ['fc']
            output: []
        wrapper:
        requires_grad: False
    student:
        adaptations:
        sequential: []
        forward_hook:
            input: ['fc']
            output: []
        wrapper:
        requires_grad: True
        frozen_modules: []
    apex:
        requires: False
        opt_level: '01'
    optimizer:
        type: 'Adam'
        params:
            lr: 0.0001
    scheduler:
        type: 'MultiStepLR'
        params:
            milestones: [5, 15]
            gamma: 0.1
    criterion:
        type: 'GeneralizedCustomLoss'
        org_term:
            factor: 0.0
        sub_terms:
            pkt:
                criterion:
                    type: 'PKTLoss'
                    params:
                        student_module_path: 'fc'
                        student_module_io: 'input'
                        teacher_module_path: 'fc'
                        teacher_module_io: 'input'
                        eps: 0.0000001
                factor: 30000.0

test:
    test_data_loader:
        dataset_id: *imagenet_val
        random_sample: False
        batch_size: 1
        num_workers: 16
