datasets:
  ilsvrc2012:
    name: &dataset_name 'ilsvrc2012'
    type: 'ImageFolder'
    root: &root_dir !join ['~/dataset/', *dataset_name]
    splits:
      train:
        dataset_id: &imagenet_train !join [*dataset_name, '/train']
        params:
          root: !join [*root_dir, '/train']
          transform_params:
            - type: 'RandomResizedCrop'
              params:
                size: &input_size [224, 224]
            - type: 'RandomHorizontalFlip'
              params:
                p: 0.5
            - &totensor
              type: 'ToTensor'
              params:
            - &normalize
              type: 'Normalize'
              params:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
      val:
        dataset_id: &imagenet_val !join [*dataset_name, '/val']
        params:
          root: !join [*root_dir, '/val']
          transform_params:
            - type: 'Resize'
              params:
                size: 256
            - type: 'CenterCrop'
              params:
                size: *input_size
            - *totensor
            - *normalize

models:
  teacher_model:
    name: &teacher_model_name 'resnet34'
    params:
      num_classes: 1000
      pretrained: True
    experiment: &teacher_experiment !join [*dataset_name, '-', *teacher_model_name]
    ckpt: !join ['./resource/ckpt/ilsvrc2012/teacher/', *teacher_experiment, '.pt']
  student_model:
    name: &student_model_name 'resnet18'
    params:
      num_classes: 1000
      pretrained: False
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_name, '_from_', *teacher_model_name]
    ckpt: !join ['./resource/ckpt/ilsvrc2012/single_stage/kr/', *student_experiment, '.pt']

train:
  log_freq: 1000
  num_epochs: 100
  train_data_loader:
    dataset_id: *imagenet_train
    random_sample: True
    batch_size: 64
    num_workers: 16
    cache_output:
  val_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 128
    num_workers: 16
  teacher:
    sequential: []
    forward_hook:
      input: ['layer1.-1.relu', 'layer2.-1.relu', 'layer3.-1.relu', 'layer4.-1.relu']
      output: ['avgpool']
    wrapper: 'DataParallel'
    requires_grad: False
  student:
    adaptations:
    sequential: []
    special:
      type: 'Student4KnowledgeReview'
      params:
        abfs:
          - path: 'student_model.layer1.-1.relu'
            io: 'input'
            params:
              in_channel: 64
              mid_channel: 512
              out_channel: 64
          - path: 'student_model.layer2.-1.relu'
            io: 'input'
            params:
              in_channel: 128
              mid_channel: 512
              out_channel: 128
          - path: 'student_model.layer3.-1.relu'
            io: 'input'
            params:
              in_channel: 256
              mid_channel: 512
              out_channel: 256
          - path: 'student_model.layer4.-1.relu'
            io: 'input'
            params:
              in_channel: 512
              mid_channel: 512
              out_channel: 512
          - path: 'student_model.avgpool'
            io: 'output'
            params:
              in_channel: 512
              mid_channel: 512
              out_channel: 512
        sizes: [1, 7, 14, 28, 56]
    forward_hook:
      input: ['student_model.layer1.-1.relu', 'student_model.layer2.-1.relu', 'student_model.layer3.-1.relu', 'student_model.layer4.-1.relu']
      output: ['student_model.avgpool', 'abf_modules.0', 'abf_modules.1', 'abf_modules.2', 'abf_modules.3', 'abf_modules.4']
    wrapper:
    requires_grad: True
    frozen_modules: []
  apex:
    requires: False
    opt_level: '01'
  optimizer:
    type: 'SGD'
    params:
      lr: 0.025
      momentum: 0.9
      weight_decay: 0.0001
  scheduler:
    type: 'MultiStepLR'
    params:
      milestones: [30, 60, 90]
      gamma: 0.1
  criterion:
    type: 'GeneralizedCustomLoss'
    org_term:
      criterion:
        type: 'CrossEntropyLoss'
        params:
          reduction: 'mean'
      factor: 1.0
    sub_terms:
      layer1:
        criterion:
          type: &hcl 'HierarchicalContextLoss'
          params:
            student_module_path: 'student_model.layer1.-1.relu'
            student_module_io: 'input'
            teacher_module_path: 'layer1.-1.relu'
            teacher_module_io: 'input'
            reduction: 'mean'
            kernel_sizes: &kernel_sizes [4, 2, 1]
        factor: 1.0
      layer2:
        criterion:
          type: *hcl
          params:
            student_module_path: 'student_model.layer2.-1.relu'
            student_module_io: 'input'
            teacher_module_path: 'layer2.-1.relu'
            teacher_module_io: 'input'
            reduction: 'mean'
            kernel_sizes: *kernel_sizes
        factor: 1.0
      layer3:
        criterion:
          type: *hcl
          params:
            student_module_path: 'student_model.layer3.-1.relu'
            student_module_io: 'input'
            teacher_module_path: 'layer3.-1.relu'
            teacher_module_io: 'input'
            reduction: 'mean'
            kernel_sizes: *kernel_sizes
        factor: 1.0
      layer4:
        criterion:
          type: *hcl
          params:
            student_module_path: 'student_model.layer4.-1.relu'
            student_module_io: 'input'
            teacher_module_path: 'layer4.-1.relu'
            teacher_module_io: 'input'
            reduction: 'mean'
            kernel_sizes: *kernel_sizes
        factor: 1.0
      avgpool:
        criterion:
          type: *hcl
          params:
            student_module_path: 'student_model.avgpool'
            student_module_io: 'output'
            teacher_module_path: 'avgpool'
            teacher_module_io: 'output'
            reduction: 'mean'
            kernel_sizes: *kernel_sizes
        factor: 1.0

test:
  test_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 1
    num_workers: 16
