datasets:
  ilsvrc2012:
    name: &dataset_name 'ilsvrc2012'
    type: 'ImageFolder'
    root: &root_dir !join ['~/dataset/', *dataset_name]
    splits:
      train:
        dataset_id: &imagenet_train !join [*dataset_name, '/train']
        params:
          root: !join [*root_dir, '/train']
          transform_params:
            - type: 'RandomResizedCrop'
              params:
                size: &input_size [224, 224]
            - type: 'RandomHorizontalFlip'
              params:
                p: 0.5
            - &totensor
              type: 'ToTensor'
              params:
            - &normalize
              type: 'Normalize'
              params:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
      val:
        dataset_id: &imagenet_val !join [*dataset_name, '/val']
        params:
          root: !join [*root_dir, '/val']
          transform_params:
            - type: 'Resize'
              params:
                size: 256
            - type: 'CenterCrop'
              params:
                size: *input_size
            - *totensor
            - *normalize

models:
  teacher_model:
    name: &teacher_model_name 'resnet34'
    params:
      num_classes: 1000
      pretrained: True
    experiment: &teacher_experiment !join [*dataset_name, '-', *teacher_model_name]
    ckpt: !join ['./resource/ckpt/ilsvrc2012/teacher/', *teacher_experiment, '.pt']
  student_model:
    name: &student_model_name 'resnet18'
    params:
      num_classes: 1000
      pretrained: False
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_name, '_from_', *teacher_model_name]
    ckpt: !join ['./imagenet_1gpu/ft_normal/', *student_experiment, '.pt']

train:
  log_freq: 1000
  stage1:
    num_epochs: 1
    train_data_loader:
      dataset_id: *imagenet_train
      random_sample: True
      batch_size: 256
      num_workers: 16
      cache_output:
    val_data_loader:
      dataset_id: *imagenet_val
      random_sample: False
      batch_size: 256
      num_workers: 16
    teacher:
      sequential: []
      auxiliary_model_wrapper:
        type: &teacher4ft 'Teacher4FactorTransfer'
        params:
          minimal:
            sequential: ['conv1', 'bn1', 'relu', 'maxpool', 'layer1', 'layer2', 'layer3', 'layer4']
          input_module_path: &teacher4ft_in_module 'teacher_model.layer4'
          paraphraser_params: &teacher4ft_paraphraser_params
            k: 0.5
            num_input_channels: 512
            kernel_size: 3
            stride: 1
            padding: 1
            uses_bn: False
          paraphraser_ckpt: &teacher4ft_paraphraser_ckpt !join ['./imagenet/ft/', *student_experiment, '_paraphraser.pt']
          uses_decoder: True
      forward_hook:
        input: []
        output: ['teacher_model.layer4', 'paraphraser']
      wrapper:
      requires_grad: True
      frozen_modules: ['teacher_model']
    student:
      adaptations:
      auxiliary_model_wrapper:
        type: 'EmptyModule'
        params:
      sequential: []
      forward_hook:
        input: []
        output: []
      wrapper:
      requires_grad: False
    optimizer:
      type: 'SGD'
      params:
        lr: 0.01
        momentum: 0.9
        weight_decay: 0.0001
    criterion:
      type: 'WeightedSumLoss'
      model_term:
        factor: 0.0
      sub_terms:
        reconst:
          criterion:
            type: 'MSELoss'
            params:
              reduction: 'mean'
          params:
            input:
              is_from_teacher: True
              module_path: 'paraphraser'
              io: 'output'
            target:
              is_from_teacher: True
              module_path: 'teacher_model.layer4'
              io: 'output'
          factor: 1.0
  stage2:
    num_epochs: 90
    train_data_loader:
      dataset_id: *imagenet_train
      random_sample: True
      batch_size: 256
      num_workers: 16
      cache_output:
    teacher:
      sequential: []
      auxiliary_model_wrapper:
        type: *teacher4ft
        params:
          minimal:
          input_module_path: *teacher4ft_in_module
          paraphraser_params: *teacher4ft_paraphraser_params
          paraphraser_ckpt: *teacher4ft_paraphraser_ckpt
          uses_decoder: False
      forward_hook:
        input: []
        output: ['teacher_model.layer4', 'paraphraser']
      wrapper:
      requires_grad: False
    student:
      adaptations:
      sequential: []
      auxiliary_model_wrapper:
        type: 'Student4FactorTransfer'
        params:
          input_module_path: 'student_model.layer4'
          translator_params:
            num_input_channels: 512
            num_output_channels: 256
            kernel_size: 3
            stride: 1
            padding: 1
            uses_bn: False
      forward_hook:
        input: []
        output: ['student_model.layer4', 'translator']
      wrapper:
      requires_grad: True
      frozen_modules: []
    optimizer:
      type: 'SGD'
      params:
        lr: 0.1
        momentum: 0.9
        weight_decay: 0.0001
    scheduler:
      type: 'MultiStepLR'
      params:
        milestones: [30, 60, 90]
        gamma: 0.1
    criterion:
      type: 'WeightedSumLoss'
      model_term:
        criterion:
          type: 'CrossEntropyLoss'
          params:
            reduction: 'mean'
        factor: 1.0
      sub_terms:
        factor_transfer:
          criterion:
            type: 'FTLoss'
            params:
              p: 1
              reduction: 'mean'
              paraphraser_path: 'paraphraser'
              translator_path: 'translator'
          factor: 1000.0

test:
  test_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 1
    num_workers: 16
