datasets:
  glue:
    name: &dataset_name 'rte'
    raw_data_kwargs:
      train_file_path:
      valid_file_path:
    dataset_id_map:
      train: &glue_train !join [*dataset_name, '/train']
      validation: &glue_val !join [*dataset_name, '/val']
      test: &glue_test !join [*dataset_name, '/test']

models:
  student_model:
    key: &student_model_key 'bert-base-uncased'
    model_name_or_path: *student_model_key
    config_kwargs:
      pretrained_model_name_or_path: *student_model_key
      num_labels: 2
    tokenizer_kwargs:
      pretrained_model_name_or_path: *student_model_key
      do_lower: True
      use_fast: True
    model_kwargs:
      pretrained_model_name_or_path: *student_model_key
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_key]
    src_ckpt:
    dst_ckpt: !join ['./resource/ckpt/glue/', *dataset_name, '/ce/', *student_experiment]

train:
  log_freq: 50
  num_epochs: 4
  train_data_loader:
    dataset_id: *glue_train
    random_sample: True
    batch_size: 16
    num_workers: 0
    collate_fn: 'DataCollatorWithPadding'
    requires_supp: False
    cache_output:
  val_data_loader:
    dataset_id: *glue_val
    random_sample: False
    batch_size: 32
    num_workers: 0
    collate_fn: 'DataCollatorWithPadding'
    requires_supp: False
  model:
    forward_proc: 'forward_batch_as_kwargs'
    adaptations:
    sequential: []
    wrapper:
    requires_grad: True
    frozen_modules: []
  optimizer:
    key: 'optimizer_no_decay'
    kwargs:
      optimizer_key: 'AdamW'
      lr: 5.0e-5
      weight_decay: 0.0
    filters_params: False
    max_grad_norm: 1.0
    grad_accum_step: 1
  scheduler:
    key: 'get_linear_schedule_with_warmup'
    kwargs:
      num_warmup_steps: 0
      num_training_steps:
    scheduling_step: 1
  criterion:
    key: 'WeightedSumLoss'
    func2extract_model_loss: 'extract_transformers_loss'
    kwargs:
      model_term:
        weight: 1.0

test:
  test_data_loader:
    dataset_id: *glue_val
    random_sample: False
    batch_size: 32
    num_workers: 0
    collate_fn: 'DataCollatorWithPadding'

private:
  - private_data_loader:
      dataset_id: *glue_test
      task_name: rte
      random_sample: False
      batch_size: 32
      num_workers: 0
      collate_fn: 'DataCollatorWithPadding'
    idx2str: True
    pred_output: 'RTE.tsv'
