datasets:
  ilsvrc2012:
    name: &dataset_name 'ilsvrc2012'
    type: 'ImageFolder'
    root: &root_dir !join ['./resource/dataset/', *dataset_name]
    splits:
      train:
        dataset_id: &imagenet_train !join [*dataset_name, '/train']
        params:
          root: !join [*root_dir, '/train']
          transform_params:
            - type: 'RandomResizedCrop'
              params:
                size: &input_size [224, 224]
            - type: 'RandomHorizontalFlip'
              params:
                p: 0.5
            - &totensor
              type: 'ToTensor'
              params:
            - &normalize
              type: 'Normalize'
              params:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
      val:
        dataset_id: &imagenet_val !join [*dataset_name, '/val']
        params:
          root: !join [*root_dir, '/val']
          transform_params:
            - type: 'Resize'
              params:
                size: 256
            - type: 'CenterCrop'
              params:
                size: *input_size
            - *totensor
            - *normalize

models:
  teacher_model:
    name: &teacher_model_name 'resnet50'
    params:
      num_classes: 1000
      pretrained: True
    experiment: &teacher_experiment !join [*dataset_name, '-', *teacher_model_name]
    ckpt: !join ['./resource/ckpt/image_classification/teacher/', *teacher_experiment, '.pt']
  student_model:
    name: &student_model_name 'resnet18'
    params:
      num_classes: 1000
      pretrained: True
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_name, '_from_', *teacher_model_name]
    ckpt: !join ['./resource/ckpt/image_classification/single_stage/cckd/', *student_experiment, '.pt']

train:
  log_freq: 1000
  num_epochs: 20
  train_data_loader:
    dataset_id: *imagenet_train
    random_sample: True
    batch_size: 32
    num_workers: 16
    cache_output:
  val_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 32
    num_workers: 16
  teacher:
    sequential: []
    special:
      type: 'Linear4CCKD'
      params:
        input_module:
          path: 'model.avgpool'
          io: 'output'
        linear_params:
          in_features: 2048
          out_features: 128
          bias: True
    forward_hook:
      input: []
      output: ['model.avgpool', 'linear']
    wrapper:
    requires_grad: True
    frozen_modules: ['model']
  student:
    adaptations:
    sequential: []
    special:
      type: 'Linear4CCKD'
      params:
        input_module:
          path: 'model.avgpool'
          io: 'output'
        linear_params:
          in_features: 512
          out_features: 128
          bias: True
    forward_hook:
      input: []
      output: ['model.avgpool', 'linear']
    wrapper:
    requires_grad: True
    frozen_modules: []
  apex:
    requires: False
    opt_level: '01'
  optimizer:
    type: 'SGD'
    params:
      lr: 0.0001
      momentum: 0.9
      weight_decay: 0.0005
  scheduler:
    type: 'MultiStepLR'
    params:
      milestones: [5, 15]
      gamma: 0.1
  criterion:
    type: 'GeneralizedCustomLoss'
    org_term:
      criterion:
        type: 'KDLoss'
        params:
          temperature: 1.0
          alpha: 0
          reduction: 'batchmean'
      factor: 1.0
    sub_terms:
      cckd:
        criterion:
          type: 'CCKDLoss'
          params:
            teacher_linear_path: 'linear'
            student_linear_path: 'linear'
            kernel_params:
              type: 'gaussian'
              gamma: 0.4
              max_p: 2
            reduction: 'batchmean'
        factor: 0.003

test:
  test_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 1
    num_workers: 16
