datasets:
  ilsvrc2012:
    name: &dataset_name 'ilsvrc2012'
    key: 'ImageFolder'
    root: &root_dir !join ['./resource/dataset/', *dataset_name]
    splits:
      train:
        dataset_id: &imagenet_train !join [*dataset_name, '/train']
        kwargs:
          root: !join [*root_dir, '/train']
          transform_configs:
            - key: 'RandomResizedCrop'
              kwargs:
                size: &input_size [224, 224]
            - key: 'RandomHorizontalFlip'
              kwargs:
                p: 0.5
            - &totensor
              key: 'ToTensor'
              kwargs:
            - &normalize
              key: 'Normalize'
              kwargs:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
      val:
        dataset_id: &imagenet_val !join [*dataset_name, '/val']
        kwargs:
          root: !join [*root_dir, '/val']
          transform_configs:
            - key: 'Resize'
              kwargs:
                size: 256
            - key: 'CenterCrop'
              kwargs:
                size: *input_size
            - *totensor
            - *normalize

models:
  teacher_model:
    key: &teacher_model_key 'inception_v3'
    kwargs:
      num_classes: 1000
      pretrained: True
    experiment: &teacher_experiment !join [*dataset_name, '-', *teacher_model_key]
    ckpt: !join ['./resource/ckpt/ilsvrc2012/teacher/', *teacher_experiment, '.pt']
  student_model:
    key: &student_model_key 'custom_inception_v3'
    kwargs:
      bottleneck_channel: 12
      bottleneck_idx: 7
      compressor:
      decompressor:
      num_classes: 1000
      pretrained: True
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_key, '_from_', *teacher_model_key]
    ckpt: !join ['./resource/ckpt/ilsvrc2012/single_stage/ghnd/', *student_experiment, '.pt']

train:
  log_freq: 1000
  num_epochs: 20
  train_data_loader:
    dataset_id: *imagenet_train
    random_sample: True
    batch_size: 32
    num_workers: 16
    cache_output:
  val_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 32
    num_workers: 16
  teacher:
    adaptations:
      maxpool1:
        key: 'MaxPool2d'
        kwargs:
          kernel_size: 3
          stride: 2
      maxpool2:
        key: 'MaxPool2d'
        kwargs:
          kernel_size: 3
          stride: 2
    sequential: ['Conv2d_1a_3x3', 'Conv2d_2a_3x3', 'Conv2d_2b_3x3', '+maxpool1', 'Conv2d_3b_1x1', 'Conv2d_4a_3x3', '+maxpool2', 'Mixed_5b', 'Mixed_5c', 'Mixed_5d', 'Mixed_6a', 'Mixed_6b', 'Mixed_6c', 'Mixed_6d', 'Mixed_6e', 'Mixed_7a', 'Mixed_7b', 'Mixed_7c']
    frozen_modules: []
    forward_hook:
      input: []
      output: ['+maxpool2', 'Mixed_5d', 'Mixed_6e', 'Mixed_7c']
    wrapper: 'DistributedDataParallel'
    requires_grad: False
  student:
    adaptations:
    sequential: ['bottleneck', 'Mixed_5b', 'Mixed_5c', 'Mixed_5d', 'Mixed_6a', 'Mixed_6b', 'Mixed_6c', 'Mixed_6d', 'Mixed_6e', 'Mixed_7a', 'Mixed_7b', 'Mixed_7c']
    frozen_modules: ['Mixed_5b', 'Mixed_5c', 'Mixed_5d', 'Mixed_6a', 'Mixed_6b', 'Mixed_6c', 'Mixed_6d', 'Mixed_6e', 'Mixed_7a', 'Mixed_7b', 'Mixed_7c']
    forward_hook:
      input: []
      output: ['bottleneck', 'Mixed_5d', 'Mixed_6e', 'Mixed_7c']
    wrapper: 'DistributedDataParallel'
    requires_grad: True
  optimizer:
    key: 'Adam'
    kwargs:
      lr: 0.001
  scheduler:
    key: 'MultiStepLR'
    kwargs:
      milestones: [5, 10, 15]
      gamma: 0.1
  criterion:
    key: 'WeightedSumLoss'
    kwargs:
      sub_terms:
        maxpool2:
          criterion:
            key: 'MSELoss'
            kwargs:
              reduction: 'sum'
          criterion_wrapper:
            key: 'SimpleLossWrapper'
            kwargs:
              input:
                is_from_teacher: False
                module_path: 'bottleneck'
                io: 'output'
              target:
                is_from_teacher: True
                module_path: '+maxpool2'
                io: 'output'
          weight: 1.0
        Mixed_5d:
          criterion:
            key: 'MSELoss'
            kwargs:
              reduction: 'sum'
          criterion_wrapper:
            key: 'SimpleLossWrapper'
            kwargs:
              input:
                is_from_teacher: False
                module_path: 'Mixed_5d'
                io: 'output'
              target:
                is_from_teacher: True
                module_path: 'Mixed_5d'
                io: 'output'
          weight: 1.0
        Mixed_6e:
          criterion:
            key: 'MSELoss'
            kwargs:
              reduction: 'sum'
          criterion_wrapper:
            key: 'SimpleLossWrapper'
            kwargs:
              input:
                is_from_teacher: False
                module_path: 'Mixed_6e'
                io: 'output'
              target:
                is_from_teacher: True
                module_path: 'Mixed_6e'
                io: 'output'
          weight: 1.0
        Mixed_7c:
          criterion:
            key: 'MSELoss'
            kwargs:
              reduction: 'sum'
          criterion_wrapper:
            key: 'SimpleLossWrapper'
            kwargs:
              input:
                is_from_teacher: False
                module_path: 'Mixed_7c'
                io: 'output'
              target:
                is_from_teacher: True
                module_path: 'Mixed_7c'
                io: 'output'
          weight: 1.0

test:
  test_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 1
    num_workers: 16

