datasets:
  glue:
    name: &dataset_name 'mnli'
    raw_data_kwargs:
      train_file_path:
      valid_file_path:
    dataset_id_map:
      train: &glue_train !join [*dataset_name, '/train']
      validation_matched: &glue_val_m !join [*dataset_name, '/val_m']
      test_matched: &glue_test_m !join [*dataset_name, '/test_m']
      validation_mismatched: &glue_val_mm !join [*dataset_name, '/val_mm']
      test_mismatched: &glue_test_mm !join [*dataset_name, '/test_mm']
  glue_ax:
    key: &ax_dataset_key 'ax'
    base_split_name: 'test'
    raw_data_kwargs:
      train_file_path:
      valid_file_path:
    dataset_id_map:
      test: &glue_test_ax !join [*ax_dataset_key, '/test_ax']

models:
  teacher_model:
    key: &teacher_model_key 'bert-large-uncased'
    model_name_or_path: &teacher_model_path 'yoshitomo-matsubara/bert-large-uncased-mnli'
    num_labels: 3
    config_kwargs:
      pretrained_model_name_or_path: *teacher_model_path
    tokenizer_kwargs:
      pretrained_model_name_or_path: *teacher_model_path
      do_lower: True
      use_fast: True
    model_kwargs:
      pretrained_model_name_or_path: *teacher_model_path
  student_model:
    key: &student_model_key 'bert-base-uncased'
    model_name_or_path: *student_model_key
    num_labels: 3
    config_kwargs:
      pretrained_model_name_or_path: *student_model_key
    tokenizer_kwargs:
      pretrained_model_name_or_path: *student_model_key
      do_lower: True
      use_fast: True
    model_kwargs:
      pretrained_model_name_or_path: *student_model_key
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_key, '_from_', *teacher_model_key]
    src_ckpt:
    dst_ckpt: !join ['./resource/ckpt/glue/', *dataset_name, '/kd/', *student_experiment]

train:
  log_freq: 1000
  num_epochs: 3
  train_data_loader:
    dataset_id: *glue_train
    random_sample: True
    batch_size: 32
    num_workers: 0
    collate_fn: 'DataCollatorWithPadding'
    requires_supp: False
    cache_output:
  val_data_loader:
    dataset_id: *glue_val_m
    random_sample: False
    batch_size: 32
    num_workers: 0
    collate_fn: 'DataCollatorWithPadding'
    requires_supp: False
  teacher:
    forward_proc: 'forward_batch_as_kwargs'
    adaptations:
    sequential: []
    wrapper:
    requires_grad: False
    frozen_modules: []
  student:
    forward_proc: 'forward_batch_as_kwargs'
    adaptations:
    sequential: []
    wrapper:
    requires_grad: True
    frozen_modules: []
  optimizer:
    key: 'optimizer_no_decay'
    kwargs:
      optimizer_key: 'AdamW'
      lr: 1.0e-4
      weight_decay: 0.0
    filters_params: False
    max_grad_norm: 1.0
    grad_accum_step: 1
  scheduler:
    key: 'get_linear_schedule_with_warmup'
    kwargs:
      num_warmup_steps: 0
      num_training_steps:
    scheduling_step: 1
  criterion:
    key: 'WeightedSumLoss'
    kwargs:
      sub_terms:
        kd:
          criterion:
            key: 'KDLoss'
            kwargs:
              student_module_path: '.classifier'
              student_module_io: 'output'
              teacher_module_path: '.classifier'
              teacher_module_io: 'output'
              temperature: 5.0
              alpha: 0.9
              reduction: 'batchmean'
          weight: 1.0

test:
  test_data_loader:
    dataset_id: *glue_val_m
    random_sample: False
    batch_size: 32
    num_workers: 0
    collate_fn: 'DataCollatorWithPadding'

private:
  - private_data_loader:
      dataset_id: *glue_test_m
      task_name: mnli
      random_sample: False
      batch_size: 32
      num_workers: 0
      collate_fn: 'DataCollatorWithPadding'
    idx2str: True
    pred_output: 'MNLI-m.tsv'
  - private_data_loader:
      dataset_id: *glue_test_mm
      task_name: mnli
      random_sample: False
      batch_size: 32
      num_workers: 0
      collate_fn: 'DataCollatorWithPadding'
    idx2str: True
    pred_output: 'MNLI-mm.tsv'
  - private_data_loader:
      dataset_id: *glue_test_ax
      task_name: ax
      random_sample: False
      batch_size: 32
      num_workers: 0
      collate_fn: 'DataCollatorWithPadding'
    idx2str: True
    pred_output: 'AX.tsv'
